version: '2'
services:

  data:
    container_name: flask_data
    image: mysql:latest
    volumes:
      - /var/lib/mysql
    command: "true"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
    volumes_from:
      - data
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 3131:3131
